version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Creating production build...
      - npm run build
      - bucket_name="elasticbeanstalk-us-east-2-1254896325"
        if aws s3 ls "s3://$bucket_name" 2>&1 | grep -q 'NoSuchBucket'; then
          echo "Bucket Does not exist. Creating bucket $bucket_name"
          aws s3 mb "s3://$bucket_name"
        else
          echo "Bucket $bucket_name already exists. Skipping creation."
        fi

  build:
    commands:
      - echo Uploading application to S3 bucket...
      - aws s3 cp --recursive ./build s3://elasticbeanstalk-us-east-2-1254896325/

artifacts:
  files:
    - "**/*"

  discard-paths: yes

cache:
  paths:
    - node_modules/
