version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Creating production build...
      - npm run build

  build:
    commands:
      - echo Uploading application to S3 bucket...
      - aws s3 cp --recursive ./build s3://elasticbeanstalk-us-east-2-1254896325/

artifacts:
  files:
    - "**/*"

  discard-paths: yes

cache:
  paths:
    - node_modules/
